//one entry point per skill type - no more istype ladders
/obj/Skills/proc/Use(mob/user, noGCD = FALSE)
	return
/obj/Skills/Projectile/Use(mob/user, noGCD = FALSE)
	return user.UseProjectile(src, noGCD)
/obj/Skills/AutoHit/Use(mob/user, noGCD = FALSE)
	return user.Activate(src, noGCD = noGCD)
/obj/Skills/Queue/Use(mob/user, noGCD = FALSE)
	return user.SetQueue(src, noGCD)
/obj/Skills/Grapple/Use(mob/user, noGCD = FALSE)
	return Activate(user, noGCD)
/obj/Skills/Teleport/Use(mob/user, noGCD = FALSE)
	return Activate(user, noGCD)
/obj/Skills/Buffs/Use(mob/user, noGCD = FALSE)
	return user.UseBuff(src, noGCD = noGCD)

mob/proc/GetAndUseSkill(obj/Skills/S, list2search = Skills, learnSkillIfMissing = FALSE, noGCD = TRUE)
	var/obj/Skills/use = locate(S, list2search)
	if(!use && learnSkillIfMissing)
		AddSkill(new S)
		use = locate(S, list2search)
	if(use)
		use.Use(src, noGCD)
