//one entry point per skill type - no more istype ladders
/obj/Skills/proc/Use(mob/user)
	return
/obj/Skills/Projectile/Use(mob/user)
	return user.UseProjectile(src)
/obj/Skills/AutoHit/Use(mob/user)
	return user.Activate(src)
/obj/Skills/Queue/Use(mob/user)
	return user.SetQueue(src)
/obj/Skills/Grapple/Use(mob/user)
	return Activate(user)
/obj/Skills/Teleport/Use(mob/user)
	return Activate(user)
/obj/Skills/Buffs/Use(mob/user)
	return user.UseBuff(src)

mob/proc/GetAndUseSkill(obj/Skills/S, list2search = Skills, learnSkillIfMissing = FALSE)
	var/obj/Skills/use = locate(S, list2search)
	if(!use && learnSkillIfMissing)
		AddSkill(new S)
		use = locate(S, list2search)
	if(use)
		use.Use(src)
