#define DEV_PER_MINUTE(n) (n)
#define DEV_PER_HOUR(n) ((n) / 60)
#define DEV_PER_DAY(n) ((n) / 1440)

#define DEV_HOPPER_CAP 10
#define DEV_POWER_TICK 100
#define DEV_EMP_STALL 300

#define DEV_DRAIN_ALARM 1
#define DEV_DRAIN_TOWER 1
#define DEV_DRAIN_PROJECTOR 0.2
#define DEV_DRAIN_CLOAK_FIELD 0.5

#define DEV_ALARM_RADIUS 3
#define DEV_ALARM_COOLDOWN 300
#define DEV_ALARM_HEAR 10

#define DEV_LAMP_RADIUS 3
#define DEV_STREET_RADIUS 5
#define DEV_LAMP_COLOR "#ffe4c2"
#define DEV_LAMP_ALPHA 170

#define DEV_SIGN_MAX 40
#define DEV_SIGN_WIDTH 160
#define DEV_SIGN_HEIGHT 32
#define DEV_SIGN_RISE 30

#define DEV_REPAIR_TIME 50

#define DEV_DUMMY_RESET 300
#define DEV_DUMMY_DPS_WINDOW 100

#define DEV_AID_CAP 10
#define DEV_AID_COOLDOWN 3000

#define DEV_CLOAK_USES 10
#define DEV_CLOAK_TICK 600
#define DEV_CLOAK_INVISIBLE 20
#define DEV_CLOAK_FIELD_RADIUS 5
#define DEV_CLOAK_FIELD_INVIS 70
#define DEV_REVEAL_SECS 3

#define DEV_EMITTER_PULSE 20
#define DEV_BURST_RADIUS 10
#define DEV_TOWER_BURST_CD 3000
#define DEV_PORTABLE_BURST_CD 36000
#define DEV_PORTABLE_MULT 0.6
#define DEV_GRAV_RADIUS 5
#define DEV_GRAV_SLOW 10
#define DEV_JAM_RADIUS 8
#define DEV_RAIN_HOLD 300
