#define ORD_BELT_CD 6
#define ORD_MINE_HOLD 10
#define ORD_THROW_RANGE 4
#define ORD_FLARE_RANGE 3
#define ORD_BOLA_RANGE 4
#define ORD_THROW_SPEED 2

#define ORD_FRAG_DAMAGE 0.8
#define ORD_FRAG_RADIUS 1
#define ORD_FLASH_RADIUS 1
#define ORD_FLASH_CONFUSE 20
#define ORD_EMP_RADIUS 2
#define ORD_EMP_STRENGTH 1
#define ORD_BOLA_CRIPPLE 15

#define ORD_CLOUD_LIFE 80
#define ORD_SMOKE_TICK 5
#define ORD_SMOKE_HOLD 8
#define ORD_GAS_TICK 10
#define ORD_GAS_POISON 3

#define ORD_CALTROP_LIFE 600
#define ORD_CALTROP_CRIPPLE 15
#define ORD_CALTROP_HIT 0.5
#define ORD_CALTROP_REARM 10

#define ORD_MINE_ARM 20
#define ORD_MINE_LIFE 6000

#define ORD_FLARE_LIFE 600
#define ORD_FLARE_PULSE 20
#define ORD_FLARE_REVEAL 3

#define ORD_BREACH_TIME 100

#define ORD_EMP_CHIP_SECS 5
#define ORD_EMP_SHIELD_TRIES 10
#define ORD_EMP_SHIELD_WAIT 5
